/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/

//answer: 4,613,732

var fib = [0,1]; // set first two fib array values. 1 and 2.
var i = 0;
var sum = 0;
while (fib[0] + fib[1] < 4000000){ // Cond: whilst the first & second values of the array are <4Million, loop will run. (the value of fib[0] & fib[1] increases with every loop, the initial values have been set - 1 & 2)
  //initiate while loop.
    i = fib[0] + fib[1]; //change value of the variable (i) to the sum of generated (fib[0] +fib[1])
    fib[0] = fib[1]; // change value of fib[0] to 1, so sequence starts with 1. Also, value of initial fib = 1
    fib[1] = i; // change value of (i) to new value of

        if(i % 2 === 0){ // check if i divides by 2 without a remainder i.e its an even number
        sum += i; //The value of sum: sum += i is same as sum = sum + i
    }
}
console.log(sum); // log to console the value of sum
